// TODO: Figure out why Mantle and zkEVM are not working
// TODO: test Metis and Mantle from the backend calls

export const networkTransferMappings: { [key: string]: string[] } = {
  "Polygon zkEVM Testnet": [
    "Goerli",
    // "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  Sepolia: [
    "Goerli",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  Goerli: [
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
    "Metis Goerli",
  ],
  "Arbitrum Goerli": [
    "Goerli",
    "Sepolia",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Optimism Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Base Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Linea Goerli Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Binance Smart Chain Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Polygon Mumbai": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Mantle Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Metis Goerli",
  ],
  "Metis Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
  ],
  Base: [
    "OP Mainnet",
    "Arbitrum One",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Metis",
  ],
  "OP Mainnet": [
    "Base",
    "Arbitrum One",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Metis",
  ],
  "Arbitrum One": [
    "Base",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Metis",
  ],
  "BNB Smart Chain": [
    "Base",
    "OP Mainnet",
    "Arbitrum One",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Metis",
  ],
  Polygon: [
    "Base",
    "OP Mainnet",
    "Arbitrum One",
    "BNB Smart Chain",
    "Polygon zkEVM",
    "Mantle",
    "Metis",
  ],
  "Polygon zkEVM": [
    "Base",
    "OP Mainnet",
    "Arbitrum One",
    "BNB Smart Chain",
    "Polygon",
    "Mantle",
    "Metis",
  ],
  Mantle: [
    "Base",
    "OP Mainnet",
    "Arbitrum One",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
  ],
  Metis: [
    "Base",
    "OP Mainnet",
    "Arbitrum One",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
  ],
};
