export const networkTransferMappings: { [key: string]: string[] } = {
  "Polygon zkEVM Testnet": [
    "Goerli",
    // "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  Sepolia: [
    "Goerli",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
    "Arbitrum",
    "Optimism",
  ],
  Goerli: [
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
    "Metis Goerli",
  ],
  "Arbitrum Goerli": [
    "Goerli",
    "Sepolia",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Optimism Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Base Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Linea Goerli Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Binance Smart Chain Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Polygon Mumbai": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Mantle Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Metis Goerli",
  ],
  "Metis Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
  ],

  // MAINNET MAPPINGS

  Base: [
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Kava",
    "Moonbeam",
    "Moonriver",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Scroll",
  ],
  Linea: [
    "Base",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Celo",
    "Kava",
    "Moonriver",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Scroll",
  ],
  "Arbitrum One": [
    "Base",
    "Linea",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava",
    "Sepolia",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
  ],
  "Arbitrum Nova": [
    "Base",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava",
    "Moonbeam",
    "Tenet",
    "Meter",
  ],
  "OP Mainnet": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava",
    "Sepolia",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
  ],
  opBNB: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Avalanche",
    "Fantom",
  ],
  Scroll: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Avalanche",
  ],
  "zkSync Era": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava",
    "Tenet",
    "Meter",
    "opBNB",
    "Astar",
    "Conflux",
    "Scroll",
  ],
  Zora: ["Base", "Linea", "Arbitrum One", "OP Mainnet", "Polygon"],
  "BNB Smart Chain": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
  ],
  Polygon: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
  ],
  "Polygon zkEVM": [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Celo",
    "Kava",
    "opBNB",
    "Astar",
    "Scroll",
  ],
  Mantle: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Avalanche",
    "Fantom",
    "Telos",
  ],
  Metis: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "Tenet",
    "Meter",
  ],
  "Core Dao": [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
  ],
  Avalanche: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava",
    "DFK",
    "Dexalot",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
  ],
  Fantom: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Harmony One",
    "Celo",
    "Kava",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Tenet",
    "Meter",
    "Beam",
    "opBNB",
  ],
  Celo: [
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Fuse",
    "Conflux",
  ],
  Moonbeam: [
    "Base",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Harmony One",
    "DFK",
  ],
  Moonriver: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Fantom",
    "Kava",
  ],
  Canto: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Fantom",
    "Tenet",
    "Meter",
  ],
  "Harmony One": [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "DFK",
    "Moonbeam",
  ],
  Fuse: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Gnosis",
    "Avalanche",
    "Celo",
    "Klaytn",
  ],
  Meter: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Tenet",
  ],
  Aurora: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
  ],
  Klaytn: ["BNB Smart Chain", "Metis", "Gnosis", "Avalanche", "DFK", "Fuse"],
  Astar: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Avalanche",
  ],
  Tenet: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Meter",
  ],
  Kava: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Avalanche",
    "Fantom",
    "Moonriver",
  ],
};
