export const getONFTEnvVarName = (fromNetwork: string): string | undefined => {
  switch (fromNetwork) {
    case "ZKEVM":
      return process.env.NEXT_PUBLIC_ZKEVM_CONTRACT_ADDRESS;
    case "OPTIMISM":
      return process.env.NEXT_PUBLIC_OPTIMISM_CONTRACT_ADDRESS;
    case "ARBITRUM":
      return process.env.NEXT_PUBLIC_ARBITRUM_CONTRACT_ADDRESS;
    case "BSC":
      return process.env.NEXT_PUBLIC_BSC_CONTRACT_ADDRESS;
    case "POLYGON":
      return process.env.NEXT_PUBLIC_POLYGON_CONTRACT_ADDRESS;
    case "BASE":
      return process.env.NEXT_PUBLIC_BASE_CONTRACT_ADDRESS;
    case "LINEA":
      return process.env.NEXT_PUBLIC_LINEA_CONTRACT_ADDRESS;
    case "METIS":
      return process.env.NEXT_PUBLIC_METIS_CONTRACT_ADDRESS;
    case "COREDAO":
      return process.env.NEXT_PUBLIC_COREDAO_CONTRACT_ADDRESS;
    case "MANTLE":
      return process.env.NEXT_PUBLIC_MANTLE_CONTRACT_ADDRESS;
    case "AVALANCHE":
      return process.env.NEXT_PUBLIC_AVALANCHE_CONTRACT_ADDRESS;
    case "FANTOM":
      return process.env.NEXT_PUBLIC_FANTOM_CONTRACT_ADDRESS;
    case "CELO":
      return process.env.NEXT_PUBLIC_CELO_CONTRACT_ADDRESS;
    case "MOONBEAM":
      return process.env.NEXT_PUBLIC_MOONBEAM_CONTRACT_ADDRESS;
    case "MOONRIVER":
      return process.env.NEXT_PUBLIC_MOONRIVER_CONTRACT_ADDRESS;
    case "ZORA":
      return process.env.NEXT_PUBLIC_ZORA_CONTRACT_ADDRESS;
    case "CANTO":
      return process.env.NEXT_PUBLIC_CANTO_CONTRACT_ADDRESS;
    case "HARMONY":
      return process.env.NEXT_PUBLIC_HARMONY_CONTRACT_ADDRESS;
    case "ZKSYNC":
      return process.env.NEXT_PUBLIC_ZKSYNC_CONTRACT_ADDRESS;
    case "OPBNB":
      return process.env.NEXT_PUBLIC_OPBNB_CONTRACT_ADDRESS;
    case "SCROLL":
      return process.env.NEXT_PUBLIC_SCROLL_CONTRACT_ADDRESS;
    case "FUSE":
      return process.env.NEXT_PUBLIC_FUSE_CONTRACT_ADDRESS;
    case "TENET":
      return process.env.NEXT_PUBLIC_TENET_CONTRACT_ADDRESS;
    case "METER":
      return process.env.NEXT_PUBLIC_METER_CONTRACT_ADDRESS;
    case "KLAYTN":
      return process.env.NEXT_PUBLIC_KLAYTN_CONTRACT_ADDRESS;
    case "ARBITRUM-NOVA":
      return process.env.NEXT_PUBLIC_ARBITRUM_NOVA_CONTRACT_ADDRESS;
    case "ASTAR":
      return process.env.NEXT_PUBLIC_ASTAR_CONTRACT_ADDRESS;
    case "KAVA":
      return process.env.NEXT_PUBLIC_KAVA_CONTRACT_ADDRESS;
    case "AURORA":
      return process.env.NEXT_PUBLIC_AURORA_CONTRACT_ADDRESS;
    case "MANTA":
      return process.env.NEXT_PUBLIC_MANTA_CONTRACT_ADDRESS;
    case "PGN":
      return process.env.NEXT_PUBLIC_PGN_CONTRACT_ADDRESS;
    default:
      return "";
  }
};
