export const layerZeroMapping = {
  "Polygon zkEVM Testnet": [
    "Goerli",
    // "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  Sepolia: [
    "Goerli",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
    "Arbitrum",
    "Optimism",
  ],
  Goerli: [
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
    "Metis Goerli",
  ],
  "Arbitrum Goerli": [
    "Goerli",
    "Sepolia",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Optimism Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Base Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Linea Goerli Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Binance Smart Chain Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Polygon Mumbai": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Mantle Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Metis Goerli",
  ],
  "Metis Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
  ],

  // MAINNET MAPPINGS

  Base: [
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava EVM",
    "Moonbeam",
    "Moonriver",
    "Klaytn",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Scroll",
  ],
  Linea: [
    "Base",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "Moonbeam",
    "Moonriver",
    "Klaytn",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Scroll",
  ],
  "Arbitrum One": [
    "Base",
    "Linea",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "Sepolia",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
    "Manta Pacific",
    "PGN",
  ],
  "Arbitrum Nova": [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava EVM",
    "Moonbeam",
    "Tenet",
    "Meter",
    "Telos",
  ],
  "OP Mainnet": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "Sepolia",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
    "Manta Pacific",
    "PGN",
  ],
  opBNB: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Avalanche",
    "Fantom",
    "Scroll",
  ],
  Scroll: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Kava EVM",
    "Moonbeam",
    "Moonriver",
    "Klaytn",
    "opBNB",
  ],
  "zkSync Era": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava EVM",
    "Klaytn",
    "Tenet",
    "Meter",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Scroll",
  ],
  Zora: ["Base", "Linea", "Arbitrum One", "OP Mainnet", "Polygon"],
  "BNB Smart Chain": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
    "Manta Pacific",
    "PGN",
  ],
  Polygon: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
    "Manta Pacific",
    "PGN",
  ],
  "Polygon zkEVM": [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Celo",
    "Kava EVM",
    "Moonbeam",
    "opBNB",
    "Astar",
    "Scroll",
  ],
  Mantle: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Kava EVM",
    "Moonbeam",
    "Klaytn",
    "Telos",
    "Scroll",
  ],
  Metis: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava EVM",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "Tenet",
    "Meter",
    "Scroll",
  ],
  "Core Dao": [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
  ],
  Avalanche: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "DFK",
    "Dexalot",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
    "Manta Pacific",
    "PGN",
  ],
  Fantom: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Tenet",
    "Meter",
    "Beam",
    "opBNB",
    "Telos",
    "Scroll",
  ],
  Celo: [
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Gnosis",
    "Avalanche",
    "Fantom",
    "Moonbeam",
    "Fuse",
    "Conflux",
  ],
  Moonbeam: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "DFK",
    "Klaytn",
    "Astar",
    "Conflux",
    "Scroll",
  ],
  Moonriver: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Fantom",
    "Kava EVM",
    "Scroll",
  ],
  Canto: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Fantom",
    "Tenet",
    "Meter",
  ],
  "Harmony One": [
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "DFK",
    "Moonbeam",
  ],
  Fuse: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Gnosis",
    "Avalanche",
    "Celo",
    "Klaytn",
  ],
  Meter: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Tenet",
  ],
  Aurora: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Telos",
  ],
  Klaytn: ["BNB Smart Chain", "Metis", "Gnosis", "Avalanche", "DFK", "Fuse"],
  Astar: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Avalanche",
    "Canto",
    "Kava EVM",
    "Moonbeam",
    "Klaytn",
    "Conflux",
  ],
  Tenet: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Meter",
  ],
  "Manta Pacific": [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "PGN",
  ],
  PGN: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Manta Pacific",
  ],
  "Kava EVM": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Avalanche",
    "Canto",
    "Fantom",
    "Moonbeam",
    "Moonriver",
    "Klaytn",
    "Astar",
    "Conflux",
    "Telos",
    "Scroll",
  ],
};
