import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Main from "../components/ONFT/Main";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col justify-between items-center min-h-screen">
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Navbar />
      <main className="flex flex-col justify-center items-center gap-4 bg-base-300 py-8 px-4 min-w-[60vw] rounded-lg my-4">
        <Main />
      </main>

      <footer className="bg-base-200 min-w-full p-4 flex justify-center items-center">
        <a
          href="https://twitter.com/cjski_web3"
          rel="noopener noreferrer"
          target="_blank"
        >
          Made with ❤️ by CJski
        </a>
      </footer>
    </div>
  );
};

export default Home;
